### ISSUE TITLE
mapper_DESY1wl: use os.path.join to join paths

### ISSUE THREAD

**Issue by carlosggarcia** [xC-ell/DEScls#15]
The file names are being created by concatenation in https://github.com/xC-ell/DEScls/blob/1fd60c527f3487ef6153231eb4d30396716b0e48/xcell/mappers/mapper_DESY1wl.py#L67. That's unsafe as it relies on the user defining the path with an end `/`. Use `os.path.join` instead.

**Comment by carlosggarcia** [comment]
Also, in line https://github.com/xC-ell/DEScls/blob/1fd60c527f3487ef6153231eb4d30396716b0e48/xcell/mappers/mapper_DESY1wl.py#L87, fcat_bin does not hold the whole path, just the basename. That means that it saves the lite catalog in the folder you called the code from.

**Comment by carlosggarcia** [comment]
This lines https://github.com/xC-ell/DEScls/blob/1fd60c527f3487ef6153231eb4d30396716b0e48/xcell/mappers/mapper_DESY1wl.py#L89-L95 should not be inside the 'else' (so that the zbin lite catalog is created if the lite catalog or the full catalog have been loaded).

**Comment by Maquiner** [comment]
I think you are looking at a different branchAre you in tests?   From: Carlos García-GarcíaSent: 08 February 2021 16:31To: xC-ell/DESclsCc: SubscribedSubject: Re: [xC-ell/DEScls] mapper_DESY1wl: use os.path.join to join paths (#15) These lines https://github.com/xC-ell/DEScls/blob/1fd60c527f3487ef6153231eb4d30396716b0e48/xcell/mappers/mapper_DESY1wl.py#L89-L95 should not be inside the 'else' (so that the zbin lite catalog is created if the lite catalog or the full catalog have been loaded).—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by carlosggarcia** [comment]
In master. Although these lines are wrongly indexed also in `tests`. I'm just writing down the bugs I found. We can close this issue later if the merge solved them.

**Comment by Maquiner** [comment]
Ok, that’s what I thought I think the merge solves them     From: Carlos García-GarcíaSent: 08 February 2021 16:35To: xC-ell/DESclsCc: Jaime RZ; CommentSubject: Re: [xC-ell/DEScls] mapper_DESY1wl: use os.path.join to join paths (#15) In master. Although these lines are wrongly indexed also in tests. I'm just writing down the bugs I found. We can close this issue later if the merge solved them.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by carlosggarcia** [comment]
Solved in #14, already merged.
